version: '3'

# Redes Docker
networks:
    network-conversor-moeda:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.40.0/29
  
services:
    apache2-conversor-moeda:
        build:
            context: ./web
            dockerfile: Dockerfile
            args:
              buildno: 1
        container_name: web-conversor-moeda
        restart: unless-stopped
        ports:
            - 80:80/tcp
        tty: true
        volumes:
            - ../app:/var/www/html
            - ./web/scripts:/home/www/scripts
            - ./web/conf.d/app/apache2.conf:/etc/apache2/apache2.conf
            - ./web/conf.d/app/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./web/conf.d/app/php.ini:/usr/local/etc/php/php.ini
        networks: 
            network-conversor-moeda:
                ipv4_address: 10.0.40.2
